spring:
  datasource:
    url: jdbc:h2:mem:maindb
  sql:
    init:
      mode: always
      data-locations: data.sql
      schema-locations: schema.sql
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none      

  data:
    mongodb:
      host: localhost
      port: 27017
      database: library

  shell:
    interactive:
      enabled: true
    script:
      enabled: true

de:
  flapdoodle:
    mongodb:
      embedded:
        version: 4.0.2

      